### ISSUE TITLE
Integration with pdf-tools

### ISSUE THREAD

**Issue by manuel-uberti** [yitang/voca-builder#4]
Hi, thanks for this great package.

From the documentation I understood it is possible to use it with `pdf-tools`. I use `pdf-tools` almost daily, but how `voca-builder` is supposed to work with it? Do I have to select to word I want to know the meaning of? If I do so, calling `voca-builder/search-popup` throws an error: `Search failed: "<p class=\"short\">"`

**Comment by yitang** [comment]
Hi, I am glad you find this package good.

As long as the rendered pdf page is text, not image, `voca-builder` should work fine with `pdf-tools`. 

Note at this stage, `voca-builder` will only get the human readable meaning, which is written and edited by human, and for those words that hasn't, it will throws that error as well. 

`Search failed: "<p class=\"short\">"`

I presume the error you got is in this case, and this problem will be fixed in the next release of `voca-builder`, which is likely to happen in next 2-3 days. 

-Yi

**Comment by manuel-uberti** [comment]
Thanks for the explanation. Looking forward to the next release then.

**Comment by yitang** [comment]
Hi,

It turns out to be a quick fix, please see the most recent commits. It should solve the problems. 

-Yi

**Comment by manuel-uberti** [comment]
Error is different now: `Wrong type argument: wholenump, -330`

**Comment by yitang** [comment]
Hi,

unfortunately, PDF-tools render the pdf page as PNG image, as shown in the documentation. So I add a new function, `voca-builder/search` in the recent commits.  It is same as `voca-builder/search-popup`, but different in two aspects: 
1. it requires an argument, so you have to call it interactively, and provide the word you wanna look into. 
2. it shows the meaning in echo area. 

It is less elegant solution than `voca-builder/search-popup` but still can save you a lot time.

Hope you like it. 

-Yi

**Comment by manuel-uberti** [comment]
Very useful, thank you.
